services:
  coli-rich-web:
    # image: ghcr.io/gbv/coli-rich-web
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    volumes:
      - ./data:/usr/src/app/dist
    environment:
      - BASE=/
      - PORT=3454
      - VITE_LOGIN_SERVER=http://localhost:3004
    ports:
      - 3454:3454
    restart: unless-stopped
